/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloandroidtest_jni_JNITest */

#ifndef _Included_com_example_helloandroidtest_jni_JNITest
#define _Included_com_example_helloandroidtest_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloandroidtest_jni_JNITest
 * Method:    printJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloandroidtest_jni_JNITest_printJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
